// 此文件由 scripts/generate-starstone-sprite.cjs 自动生成，请勿手工修改。

export const starstoneAtlasFileName = 'opencv_starstone_zh_cn_3dfb524f349af921.png' as const;

export const starstoneAtlasSize = { width: 72, height: 992 } as const;

export const starstoneAtlasEntries = {
  'anchor.processing_title': {
    x: 0,
    y: 0,
    width: 72,
    height: 34,
  },
  'digit.candidate.blue.1': {
    x: 0,
    y: 36,
    width: 11,
    height: 13,
  },
  'digit.candidate.blue.2': {
    x: 0,
    y: 51,
    width: 11,
    height: 13,
  },
  'digit.candidate.blue.3': {
    x: 0,
    y: 66,
    width: 11,
    height: 13,
  },
  'digit.candidate.blue.4': {
    x: 0,
    y: 81,
    width: 11,
    height: 13,
  },
  'digit.candidate.green.1': {
    x: 0,
    y: 96,
    width: 11,
    height: 13,
  },
  'digit.candidate.green.2': {
    x: 0,
    y: 111,
    width: 11,
    height: 13,
  },
  'digit.candidate.green.3': {
    x: 0,
    y: 126,
    width: 11,
    height: 13,
  },
  'digit.candidate.green.4': {
    x: 0,
    y: 141,
    width: 11,
    height: 13,
  },
  'digit.candidate.red.1': {
    x: 0,
    y: 156,
    width: 11,
    height: 13,
  },
  'digit.candidate.red.2': {
    x: 0,
    y: 171,
    width: 11,
    height: 13,
  },
  'digit.candidate.red.3': {
    x: 0,
    y: 186,
    width: 11,
    height: 13,
  },
  'digit.candidate.red.4': {
    x: 0,
    y: 201,
    width: 11,
    height: 13,
  },
  'digit.candidate.refresh.1': {
    x: 0,
    y: 216,
    width: 9,
    height: 13,
  },
  'digit.candidate.refresh.2': {
    x: 0,
    y: 231,
    width: 9,
    height: 13,
  },
  'digit.candidate.yellow.1': {
    x: 0,
    y: 246,
    width: 10,
    height: 13,
  },
  'digit.candidate.yellow.2': {
    x: 0,
    y: 261,
    width: 10,
    height: 13,
  },
  'digit.candidate.yellow.3': {
    x: 0,
    y: 276,
    width: 10,
    height: 13,
  },
  'digit.candidate.yellow.4': {
    x: 0,
    y: 291,
    width: 10,
    height: 13,
  },
  'digit.cost.8': {
    x: 0,
    y: 306,
    width: 10,
    height: 15,
  },
  'digit.cost.9': {
    x: 0,
    y: 323,
    width: 10,
    height: 15,
  },
  'digit.diamond_bottom.1': {
    x: 0,
    y: 340,
    width: 10,
    height: 14,
  },
  'digit.diamond_bottom.2': {
    x: 0,
    y: 356,
    width: 10,
    height: 14,
  },
  'digit.diamond_bottom.3': {
    x: 0,
    y: 372,
    width: 10,
    height: 14,
  },
  'digit.diamond_bottom.4': {
    x: 0,
    y: 388,
    width: 10,
    height: 14,
  },
  'digit.diamond_bottom.5': {
    x: 0,
    y: 404,
    width: 10,
    height: 14,
  },
  'digit.diamond_left.1': {
    x: 0,
    y: 420,
    width: 10,
    height: 14,
  },
  'digit.diamond_left.2': {
    x: 0,
    y: 436,
    width: 10,
    height: 14,
  },
  'digit.diamond_left.3': {
    x: 0,
    y: 452,
    width: 10,
    height: 14,
  },
  'digit.diamond_left.4': {
    x: 0,
    y: 468,
    width: 10,
    height: 14,
  },
  'digit.diamond_left.5': {
    x: 0,
    y: 484,
    width: 10,
    height: 14,
  },
  'digit.diamond_right.1': {
    x: 0,
    y: 500,
    width: 10,
    height: 14,
  },
  'digit.diamond_right.2': {
    x: 0,
    y: 516,
    width: 10,
    height: 14,
  },
  'digit.diamond_right.3': {
    x: 0,
    y: 532,
    width: 10,
    height: 14,
  },
  'digit.diamond_right.4': {
    x: 0,
    y: 548,
    width: 10,
    height: 14,
  },
  'digit.diamond_right.5': {
    x: 0,
    y: 564,
    width: 10,
    height: 14,
  },
  'digit.diamond_top.1': {
    x: 0,
    y: 580,
    width: 10,
    height: 14,
  },
  'digit.diamond_top.2': {
    x: 0,
    y: 596,
    width: 10,
    height: 14,
  },
  'digit.diamond_top.3': {
    x: 0,
    y: 612,
    width: 10,
    height: 14,
  },
  'digit.diamond_top.4': {
    x: 0,
    y: 628,
    width: 10,
    height: 14,
  },
  'digit.diamond_top.5': {
    x: 0,
    y: 644,
    width: 10,
    height: 14,
  },
  'digit.max_attempts.5': {
    x: 0,
    y: 660,
    width: 11,
    height: 15,
  },
  'digit.max_attempts.7': {
    x: 0,
    y: 677,
    width: 11,
    height: 15,
  },
  'digit.max_attempts.9': {
    x: 0,
    y: 694,
    width: 11,
    height: 15,
  },
  'digit.refresh_count.0': {
    x: 0,
    y: 711,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.1': {
    x: 0,
    y: 724,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.2': {
    x: 0,
    y: 737,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.3': {
    x: 0,
    y: 750,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.4': {
    x: 0,
    y: 763,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.5': {
    x: 0,
    y: 776,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.6': {
    x: 0,
    y: 789,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.7': {
    x: 0,
    y: 802,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.8': {
    x: 0,
    y: 815,
    width: 8,
    height: 11,
  },
  'digit.refresh_count.9': {
    x: 0,
    y: 828,
    width: 8,
    height: 11,
  },
  'digit.remaining_attempts.1': {
    x: 0,
    y: 841,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.2': {
    x: 0,
    y: 858,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.3': {
    x: 0,
    y: 875,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.4': {
    x: 0,
    y: 892,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.5': {
    x: 0,
    y: 909,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.6': {
    x: 0,
    y: 926,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.7': {
    x: 0,
    y: 943,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.8': {
    x: 0,
    y: 960,
    width: 11,
    height: 15,
  },
  'digit.remaining_attempts.9': {
    x: 0,
    y: 977,
    width: 11,
    height: 15,
  },
} as const;

export type StarstoneTemplateId = keyof typeof starstoneAtlasEntries;
export type StarstoneTemplateRect = (typeof starstoneAtlasEntries)[StarstoneTemplateId];
